import { ArrowRight, BookOpen, Clock3, ExternalLink, HandHeart, Heart, MapPin, Play, Quote } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import config from "@/data/data.json";
import HeroCarousel from "./HeroCarousel";
import CopyPix from "./CopyPix";
import PrayerForm from "./PrayerForm";
import { DynamicEvents, DynamicMessages } from "./DynamicContent";

const icons = { heart: Heart, play: Play, hand: HandHeart, book: BookOpen };

export default function Home() {
  return <div id="inicio">
    <HeroCarousel />
    <section className="container-page relative z-10 -mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {config.quickLinks.map((item) => { const Icon = icons[item.icon as keyof typeof icons]; return <a key={item.title} href={item.href} className="group rounded-2xl bg-white p-5 shadow-lg hover:-translate-y-1"><Icon className="mb-5 text-[#d79a45]" size={25} /><strong className="block text-lg">{item.title}</strong><span className="mt-1 block text-sm text-[#66736d]">{item.description}</span><ArrowRight className="mt-4 text-[#1d5b4b] transition group-hover:translate-x-1" size={18} /></a>; })}
    </section>
    <section id="sobre" className="container-page grid gap-12 py-24 md:grid-cols-[1fr_1.2fr] md:items-center">
      <div><span className="eyebrow">Uma igreja para todos</span><h2 className="mt-3 text-4xl leading-tight md:text-5xl">Há um lugar à mesa para você.</h2><p className="mt-5 leading-7 text-[#66736d]">Somos uma comunidade apaixonada por Jesus, pela Bíblia e por pessoas. Aqui, você encontra espaço para ser acolhido, construir amizades e viver seu propósito.</p><a href="#contato" className="mt-7 inline-flex items-center gap-2 font-bold text-[#1d5b4b]">Conheça nossa história <ArrowRight size={18} /></a></div>
      <div className="relative overflow-hidden rounded-[2rem] bg-[#dce9df] p-8"><Quote className="text-[#d79a45]" size={38} /><p className="mt-4 font-display text-3xl leading-tight text-[#1d5b4b]">“Tudo o que fazemos começa com o desejo de ver vidas restauradas pelo amor de Deus.”</p><div className="mt-8 flex items-center gap-3"><div className="h-10 w-10 rounded-full bg-[#1d5b4b]" /><div><strong className="block">Pr. Rafael Martins</strong><span className="text-sm text-[#66736d]">Pastor titular</span></div></div></div>
    </section>
    <section id="mensagens" className="bg-[#173d32] py-24 text-white"><div className="container-page"><div className="flex items-end justify-between gap-4"><div><span className="eyebrow">Alimente sua fé</span><h2 className="mt-2 text-4xl">Mensagens recentes</h2></div><a href={config.social.youtube} target="_blank" rel="noreferrer" className="hidden items-center gap-2 text-sm font-bold sm:flex">Ver canal <ExternalLink size={16} /></a></div><DynamicMessages /></div></section>
    <section id="eventos" className="container-page py-24"><span className="eyebrow">Viva a igreja</span><h2 className="mt-2 text-4xl">Próximos eventos</h2><DynamicEvents /></section>
    <section id="contribua" className="bg-[#f0f5f0] py-20"><div className="container-page grid gap-10 md:grid-cols-[1.2fr_1fr] md:items-center"><div><span className="eyebrow">Generosidade</span><h2 className="mt-2 text-4xl">Sua contribuição transforma histórias.</h2><p className="mt-4 max-w-xl leading-7 text-[#66736d]">Contribua de forma segura e transparente para que nossa igreja continue cuidando de pessoas e servindo a cidade.</p><div className="mt-7 rounded-2xl bg-white p-5 text-sm"><p><strong>Dados bancários:</strong> {config.giving.bank}</p><p className="mt-2"><strong>Favorecido:</strong> {config.giving.holder}</p><p className="mt-2"><strong>CNPJ:</strong> {config.giving.cnpj}</p><div className="mt-5 flex flex-wrap items-center gap-3"><code className="rounded bg-[#f0f5f0] px-3 py-2">{config.giving.pix}</code><CopyPix value={config.giving.pix} /></div></div></div><div className="mx-auto rounded-3xl bg-white p-7 text-center shadow-sm"><QRCodeSVG value={config.giving.qrValue} size={170} className="mx-auto" /><p className="mt-4 text-sm font-bold">Aponte a câmera do celular</p><p className="mt-1 text-xs text-[#66736d]">QR Code PIX copia e cola</p></div></div></section>
    <section id="oracao" className="container-page grid gap-12 py-24 md:grid-cols-2"><div><span className="eyebrow">Estamos com você</span><h2 className="mt-2 text-4xl">Podemos orar por você?</h2><p className="mt-4 leading-7 text-[#66736d]">Sua história importa. Envie seu pedido e nossa equipe estará em oração.</p><div id="horarios" className="mt-8 space-y-4">{config.serviceTimes.map((service) => <div key={service.day} className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#dce9df] text-[#1d5b4b]"><Clock3 size={20} /></span><div><strong className="block">{service.day} · {service.time}</strong><span className="text-sm text-[#66736d]">{service.label}</span></div></div>)}</div></div><PrayerForm /></section>
    <section id="gceu" className="bg-[#dce9df] py-16"><div className="container-page flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><span className="eyebrow">Conexão e cuidado</span><h2 className="mt-2 text-4xl">Encontre um GCEU perto de você.</h2><p className="mt-3 text-[#66736d]">Pequenos grupos, grandes amizades e crescimento constante.</p></div><a href="#contato" className="inline-flex w-fit items-center gap-2 rounded-full bg-[#1d5b4b] px-6 py-3 font-bold text-white">Quero participar <ArrowRight size={18} /></a></div></section>
    <section id="contato" className="container-page py-20"><div className="mb-8"><span className="eyebrow">Onde estamos</span><h2 className="mt-2 text-4xl">Venha nos visitar</h2></div><div className="grid gap-4 md:grid-cols-2">{config.locations.map((location) => <a href={location.mapUrl} target="_blank" rel="noreferrer" key={location.name} className="flex items-start gap-4 rounded-2xl bg-white p-6 shadow-sm hover:shadow-md"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#dce9df] text-[#1d5b4b]"><MapPin size={20} /></span><span><strong className="block text-lg">{location.name}</strong><span className="mt-1 block text-sm text-[#66736d]">{location.address}</span></span></a>)}</div></section>
  </div>;
}
